/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'usernameFragment' : [] | [string],
  'candidate' : string,
  'sdpMid' : [] | [string],
  'sdpMLineIndex' : [] | [bigint],
}
export type Candidates = Array<Candidate>;
export interface Offer { 'sdp' : string, 'type' : string }
export type SessionId = bigint;
export type UserId = string;
export interface _SERVICE {
  'addBroadcasterCandidates' : ActorMethod<[SessionId, Candidates], undefined>,
  'addViewerCandidates' : ActorMethod<
    [SessionId, UserId, Candidates],
    undefined
  >,
  'getBroadcasterCandidates' : ActorMethod<[SessionId, UserId], Candidates>,
  'getOffer' : ActorMethod<[SessionId, UserId], Offer>,
  'getViewerCandidates' : ActorMethod<[SessionId, UserId], Candidates>,
  'joinAsViewer' : ActorMethod<[SessionId, UserId], undefined>,
  'sendAnswer' : ActorMethod<[SessionId, UserId, Offer], undefined>,
  'shouldFinish' : ActorMethod<[SessionId], boolean>,
  'startBroadcast' : ActorMethod<[UserId, Offer], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];